variables:
 CI: true
 project_name: pymap3d

stages:

- stage: SyntaxChecks
  jobs:

  - job: Py35_PEP8_MyPy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.5'
        addToPath: true
    - script: pip install -e .[lint]
      displayName: Dev install
    - script: flake8
      displayName: PEP8
    - script: mypy .
      displayName: Type Check

  - job: Py37_PEP8_MyPy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: pip install -e .[lint]
      displayName: Dev install
    - script: flake8
      displayName: PEP8
    - script: mypy .
      displayName: Type Check

- stage: PackageInstall
  jobs:

  - job: UbuntuInstall
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: |
        python setup.py install
        pip install $(project_name)[full,tests]
      displayName: hard install
    - script: |
        cd $HOME
        python -m pytest $(Build.SourcesDirectory) -r a -v
      displayName: Build Python

- stage: FallbackTests
  jobs:

  - job: Py27fallback
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7'
        addToPath: true
    - script: pip install -e .[tests]
      displayName: 'Dev install'
    - script: pytest tests/test_py27.py
      displayName: PyTest

  - job: Py34fallback
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.4'
        addToPath: true
    - script: pip install -e .[tests]
      displayName: 'Dev install'
    - script: pytest tests/test_py27.py
      displayName: PyTest


- stage: IntegrationTests
  jobs:

  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: pip install -e .[tests,full]
      displayName: 'Dev install'
    - script: pytest -r a -v
      displayName: PyTest

  - job: MacOS
    pool:
      vmImage: macos-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: pip install -e .[tests,full]
      displayName: 'Dev install'
    - script: pytest -r a -v
      displayName: PyTest

  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: pip install -e .[tests,full]
      displayName: 'Dev install'
    - script: pytest -r a -v
      displayName: PyTest

- stage: CoverageTests

  jobs:
  - job: Coverage
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'
        addToPath: true
    - script: pip install -e .[tests,full,testproj]
      displayName: Dev install
    - script: pytest --junitxml=junit/test-results.xml --cov --cov-report=xml --cov-report=html
      displayName: Coverage

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops#publish-code-coverage-results
    - task: PublishCodeCoverageResults@1
      condition: succeeded()
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
