name: ci

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci.yml
    - "!scripts/**"
    - "!examples/**"

jobs:

  full:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest]
        include:
        - os: macos-latest
          python-version: '3.14'
        - os: windows-latest
          python-version: '3.14'

    steps:
    - &checkout
      uses: actions/checkout@v6
    - &setup-python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[full,tests]

    - run: mypy --non-interactive

    - run: pytest

    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()


  coverage:
    runs-on: ubuntu-latest
    name: Coverage Python ${{ matrix.python-version }}

    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - *checkout

      - *setup-python

      - name: Install tests and lint dependencies
        run: pip install -e .[tests,coverage]

      - name: Collect coverage without NumPy
        run: pytest --cov=src --cov-report=xml

      - name: Install NumPy
        run: pip install -e .[core]

      - name: Collect coverage with NumPy
        run: pytest --cov=src --cov-report=xml --cov-append

      # - name: Install full dependencies
      #   run: pip install -e .[full]
      # - name: Test with full dependencies and collect coverage
      #   run: pytest --cov=src --cov-report=xml --cov-append

      - name: Upload coverage
        uses: codecov/codecov-action@v7
        with:
          name: Python ${{ matrix.python-version }}
