name: ci_stdlib_only

on:
  push:
    paths:
    - "**.py"
    - .github/workflows/ci_stdlib_only.yml
    - "!scripts/**"
    - "!examples/**"

jobs:

  stdlib_only:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14',
          '3.15-dev']
        os: ['ubuntu-latest']
        include:
        - os: macos-latest
          python-version: '3.14'
        - os: windows-latest
          python-version: '3.14'

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests]

    - run: pytest
